# Generated by Django 3.2 on 2021-05-03 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dmapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dm',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='dm',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='dm',
            name='receiver',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dm',
            name='sender',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
