# Generated by Django 3.2 on 2021-05-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmapp', '0002_auto_20210503_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='dm',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
